# Generated by Django 5.1.6 on 2025-10-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="currency",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
