# Generated by Django 5.1.6 on 2025-10-30 21:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("creation_timestamp", models.DateTimeField(auto_now_add=True)),
                ("modification_timestamp", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("message", models.CharField(max_length=1000)),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "ordering": ["-creation_timestamp"],
            },
        ),
    ]
