# Generated by Django 5.1.6 on 2025-10-18 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Contact", new_name="ContactUs",),
    ]
